config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :boards do
    resources :lists, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      get :confirm_destroy
    end
  end

  resources :tasks, except: %i[index show] do
    resources :subtasks, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      patch :reorder
    end
  end

  root 'boards#index'
end

app/models/list.rb
class List < ApplicationRecord
  include RankedModel

  belongs_to :board
  ranks :board_order,
        with_same: :board_id

  has_many :tasks, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: { scope: :board_id }
  validates :color_code, format: { with: /\A#?(?:[A-F0-9]{3}){1,2}\z/i, message: 'Must be a valid hex color' },
            allow_nil: true,
            allow_blank: true
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!

  def reorder
    list = current_user.lists.find(params[:id])

    if list&.update(params.permit(:board_order_position))
      render json: { message: 'List order updated.' }, status: :ok
    else
      render json: { error: 'Failed to update list order.' }, status: :unprocessable_entity
    end
  end
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/lists/_list.html.erb
<div
  id="<%= dom_id(list) %>_header"
  data-reorder-path="<%= reorder_board_list_path(list.board, list) %>"
  data-lists-target="list"
  class="flex flex-col gap-6 w-[280px]">
  <div
    class="flex items-center gap-3"
  >
    <div
      class="h-4 w-4 flex-shrink-0 rounded-full bg-main-purple"
      style="background-color: <%= list.color_code %>"
    ></div>
    <h3 class="uppercase text-heading-s text-medium-grey"><%= list.name %></h3>
    <button
      class="ml-auto flex-shrink-0 hover:cursor-grab select-none touch-none"
      data-lists-target='listDragHandle'
    >
      <%= svg_tag 'icon-drag-handle', class: "h-6 w-6 text-medium-grey" %>
    </button>
  </div>

  <div
    id="<%= dom_id(list) %>_content"
    class="flex shrink-0 grow flex-col gap-5">
    <%= render list.tasks.sort_by { |task| task[:list_order] } %>
  </div>
</div>

app/views/lists/_list_fields.html.erb
<div data-nested-form-target="item" class="flex flex-col">
  <div class="flex gap-x-4 items-center">
    <%= f.color_field :color_code, value: f.object.color_code || '#8471F2' %>
    <%= f.text_field :name, class: 'grow' %>
    <%= f.hidden_field :_destroy %>
    <button
      data-action="nested-form#removeItem"
      data-nested-form-new-record-param="<%= f.object.new_record? %>"
    >
      <%= svg_tag 'icon-cross' %>
    </button>
  </div>
  <%= field_errors(f.object, :name) %>
</div>