config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :boards do
    resources :lists, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      get :confirm_destroy
    end
  end

  resources :tasks, except: %i[index show] do
    resources :subtasks, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      patch :reorder
    end
  end

  root 'boards#index'
end

app/models/task.rb
class Task < ApplicationRecord
  include RankedModel

  belongs_to :list
  ranks :list_order, with_same: :list_id

  has_many :subtasks, dependent: :destroy
  accepts_nested_attributes_for :subtasks, reject_if: :all_blank, allow_destroy: true

  validates :title, presence: true, length: { maximum: 100 }
  validates :description, length: { maximum: 500, too_long: '%<count>s characters is the maximum allowed' }
  validates_associated :subtasks
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :authenticate_user!
  before_action :set_task, only: %i[show edit destroy update reorder]

  def new
    board = current_user.boards.find_by(id: params[:board_id])
    if board.lists&.first
      @task = Task.new(list: board.lists.first)
      2.times { @task.subtasks.build }
      p @task.subtasks
    else
      redirect_to root_path, alert: "Board wasn't found."
    end
  end

  def edit; end

  def create
    list = current_user.lists.find_by(id: params[:task][:list_id])

    if list
      @task = list.tasks.build(task_params)
      @task.list_order_position = :first
    end

    respond_to do |format|
      if @task.save

        format.turbo_stream { flash.now[:notice] = 'Task was successfully created' }
        format.html { redirect_to @task.board, notice: 'Task was successfully created' }
      else
        format.turbo_stream { flash.now[:alert] = "Task wasn't saved." }
        format.html { render :new, status: :unprocessable_entity, alert: "Task wasn't saved." }
      end
    end
  end

  def update
    @task.assign_attributes(task_params)
    @task.list_order_position = :first if @task.list_id_changed?

    respond_to do |format|
      if @task.save
        @new_list = List.includes(:board, tasks: :subtasks).find(@task.list_id)

        format.turbo_stream { flash.now[:notice] = 'Task was successfully updated!' }
        format.html { redirect_to board_path(@task.list.board), notice: 'Task was successfully updated!' }
      else
        format.turbo_stream { flash.now[:alert] = "Task wasn't updated." }
        format.html { render :edit, status: :unprocessable_entity, alert: "Task wasn't updated." }
      end
    end
  end

  def destroy
    @task.destroy
    respond_to do |format|
      format.turbo_stream
      format.html { redirect_to board_path(@task.list.board), notice: 'Task was successfully deleted.' }
    end
  end

  def reorder
    list = current_user.lists.find(params[:list_id])

    if @task && list
      @task.list_id = list.id
      @task.list_order_position = params[:list_order_position]
    end

    if @task.save
      render json: { message: 'Task order updated.' }, status: :ok
    else
      render json: { error: @task.errors.full_messages }, status: :unprocessable_entity
    end
  end

  private

  def task_params
    params.require(:task).permit(:id, :title, :description, :list_id,
                                 subtasks_attributes: %i[id title is_completed task_order_position _destroy])
  end

  def set_task
    @task = current_user.tasks.includes(:subtasks).order('subtasks.task_order').find_by(id: params[:id])
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/_form.html.erb
<%= form_with model: task,
              html: { autocomplete: false },
              id: 'task_form',
              class: 'flex flex-col gap-y-6',
              data: { controller: 'nested-form' } do |task_form| %>

  <template data-nested-form-target="template">
    <%= task_form.fields_for :subtasks, Subtask.new, child_index: 'NEW_RECORD' do |subtask_from| %>
      <%= render partial: 'subtasks/subtask_fields', locals: { f: subtask_from, idx: 0 } %>
    <% end %>
  </template>

  <h2 class="text-heading-l dark:text-white"><%= task.new_record? ? 'Add New' : 'Edit' %> Task</h2>

  <div class="field">
    <%= task_form.label :title %>
    <%= task_form.text_field :title, autofocus: true, placeholder: 'e.g. Take coffee break' %>
    <%= field_errors(task_form.object, :title) %>
  </div>

  <div class="field">
    <%= task_form.label :description %>
    <%= task_form.text_area :description, rows: 4, placeholder: 'e.g. It’s always good to take a break. This 15 minute break will recharge the batteries a little.' %>
    <%= field_errors(task_form.object, :description) %>
  </div>

  <div class="field">
    <p class="text-body-m text-medium-grey dark:text-white">Subtasks</p>
    <div class="flex flex-col gap-y-3">
      <% task.subtasks.each_with_index do |subtask, idx| %>
        <%= task_form.fields_for :subtasks, subtask do |subtask_from| %>
          <%= render partial: 'subtasks/subtask_fields', locals: { f: subtask_from, idx: idx } %>
        <% end %>
      <% end %>
      <%= button_tag '+ Add New Subtask', class: 'secondary_sm_btn', data: { 'nested-form-target': "addBtn", action: 'nested-form#addItem' } %>
    </div>
  </div>

  <div class="relative flex flex-col gap-2 mt-6">
    <%= task_form.label :list_id, "Current List" %>
    <%= task_form.collection_select :list_id,
                                    task.list.board.lists.sort_by { _1.board_order },
                                    :id, :name, {},
                                    { data: { controller: "single-select" } } %>
    <%= field_errors(task_form.object, :list_id) %>
  </div>

  <%= task_form.submit class: 'primary_sm_btn' %>

<% end %>

app/views/tasks/_show_form.html.erb
<%= form_with model: task, id: 'task_show_form', data: { controller: 'task-show-form', action: 'input->task-show-form#submit' } do |tf| %>
  <div id="subtasks" class="">
    <p class="mb-4 text-body-m text-medium-grey dark:text-white">
      Subtasks (<%= task.subtasks.select { |subtask| subtask.is_completed == true }.count %>
      of <%= task.subtasks.size %>)
    </p>
    <% unless task.subtasks.empty? %>
      <div class="flex flex-col gap-y-2">
        <% task.subtasks.sort_by { _1.created_at }.each do |subtask| %>
          <%= tf.fields_for :subtasks, subtask do |sf| %>
            <div id="<%= dom_id(subtask) %>" class="flex items-center p-3 rounded gap-x-4 text-body-m bg-light-grey hover:bg-main-purple/25 dark:hover:bg-main-purple/25 dark:bg-very-dark-grey dark:text-white">
              <%= sf.check_box :is_completed, class: 'peer' %>
              <%= sf.label :is_completed, subtask.title, class: 'peer-checked:opacity-50 peer-checked:line-through text-black' %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="flex flex-col gap-2 mt-6">
    <%= tf.label :list_id, "Current List" %>
    <%= tf.collection_select :list_id,
                             task.list.board.lists.sort_by { _1.board_order },
                             :id, :name, {},
                             { data: { controller: "single-select" } } %>
  </div>
<% end %>

app/views/tasks/_task.html.erb
<div
  id="<%= dom_id(task) %>"
  data-reorder-path="<%= reorder_task_path(task) %>"
  data-lists-target="task"
  class="flex flex-col gap-2 rounded-lg bg-white px-4 py-6 drop-shadow-md group/task dark:dark:bg-dark-grey"
>
  <div class="grid grid-flow-col items-start gap-2">
    <%= link_to board_path(task.list.board, task: task.id), data: { turbo_frame: 'modal', turbo_action: 'replace' },
                class: 'w-[220px]' do %>
      <h4 class="group-hover/task:text-main-purple text-heading-m dark:text-white break-words"><%= task.title
      %></h4>
    <% end %>

    <button
      class="ml-auto hover:cursor-grab select-none"
      data-lists-target='taskDragHandle'
    >
      <%= svg_tag 'icon-drag-handle', class: "h-6 w-6 text-medium-grey" %>
    </button>
  </div>
  <p class="text-body-m text-medium-grey">
    <%= task.subtasks.select { |subtask| subtask.is_completed == true }.count %>
    of  <%= task.subtasks.size %> subtasks</p>
</div>

app/views/tasks/create.turbo_stream.erb
<% if @task.valid? %>
  <%= turbo_stream.prepend "#{dom_id(@task.list)}_content", @task %>
<% end %>

<%= turbo_stream.replace "task_form" do %>
  <%= render partial: 'tasks/form', locals: { task: @task } %>
<% end %>

app/views/tasks/destroy.turbo_stream.erb
<%= turbo_stream.update 'modal' %>

<%= turbo_stream.remove @task %>

app/views/tasks/edit.html.erb
<%= render 'shared/modal' do %>
  <%= link_to "Back", board_path(@task.list.board, task: @task.id), class: "text-body-m text-medium-grey mb-2" %>
  <%= render partial: 'form', locals: { task: @task } %>
<% end %>

app/views/tasks/new.html.erb
<%= render 'shared/modal' do %>
  <%= render partial: 'form', locals: { task: @task } %>
<% end %>

app/views/tasks/show.html.erb
<%= render 'shared/modal' do %>

  <div class="flex flex-col gap-y-6">
    <div class="flex items-start justify-between gap-4">
      <h2 class="text-heading-l dark:text-white">
        <%= @task.title %>
      </h2>
      <%= render 'shared/dots_menu' do %>
        <%= link_to 'Edit task', edit_task_path(@task), class: 'px-4' %>
        <%= link_to 'Delete task', @task, data: { 'turbo-frame': '_top', 'turbo-method': :delete, 'turbo-confirm': 'Are you sure you want to delete this task?' }, class: 'px-4 text-red' %>
      <% end %>
    </div>

    <p class="text-body-l text-medium-grey">
      <%= @task.description %>
    </p>

    <%= render partial: 'tasks/show_form', locals: { task: @task } %>
  </div>
<% end %>

app/views/tasks/update.turbo_stream.erb
<%= turbo_stream.replace 'task_show_form' do %>
  <%= render partial: 'tasks/show_form', locals: { task: @task } %>
<% end %>

<%= turbo_stream.replace 'task_form' do %>
  <%= render partial: 'tasks/form', locals: { task: @task } %>
<% end %>

<%= turbo_stream.prepend 'flash_container', partial: 'shared/flash', locals: { flash: flash } %>

<% if @task.saved_change_to_attribute?(:list_id) %>
  <%= turbo_stream.remove dom_id(@task) %>
  <%= turbo_stream.prepend "#{dom_id(@task.list)}_content", @task %>
<% elsif @task.valid? %>
  <%= turbo_stream.replace dom_id(@task), @task %>
<% end %>