config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  resources :boards do
    resources :lists, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      get :confirm_destroy
    end
  end

  resources :tasks, except: %i[index show] do
    resources :subtasks, only: [:reorder] do
      member do
        patch :reorder
      end
    end
    member do
      patch :reorder
    end
  end

  root 'boards#index'
end

app/views/shared/_dots_menu.html.erb
<div class="relative inline-block text-left" data-controller="dots-menu">
  <div>
    <button
      data-dots-menu-target="button"
      data-action="click->dots-menu#handleToggle"
      type="button"
      class="flex justify-center w-5 rounded-full focus:outline-none"
      id="menu-button"
      aria-expanded="true"
      aria-haspopup="true"
    >
      <span class="sr-only">Open board edit menu</span>
      <%= svg_tag 'three-dots-menu' %>
    </button>
  </div>

  <div
    data-dots-menu-target="content"
    data-transition-enter="transition ease-out duration-100"
    data-transition-enter-start="transform opacity-0 scale-95"
    data-transition-enter-end="transform opacity-100 scale-100"
    data-transition-leave="transition ease-in duration-75"
    data-transition-leave-start="transform opacity-100 scale-100"
    data-transition-leave-end="transform opacity-0 scale-95"
    class="absolute right-0 z-10 hidden w-56 mt-2 origin-top-right bg-white rounded-lg shadow-lg dark:bg-dark-grey ring-1 ring-black ring-opacity-5 focus:outline-none text-body-l text-medium-grey"
    role="menu"
    aria-orientation="vertical"
    aria-labelledby="menu-button"
    tabindex="-1">
    <div
      class="flex flex-col py-4 hover:[&>a]:bg-main-purple-hover/10 [&>a]:py-2"
      role="none"
      data-dots-menu-target="linksContainer"
    >
      <%= yield %>
    </div>
  </div>
</div>

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div
    class="bg-white dark:bg-very-dark-grey shadow rounded-md <%= flash_message_classes key %> p-4"
    data-controller="flash"
    data-transition-enter="transform ease-out duration-300 transition"
    data-transition-enter-start="-translate-y-20 opacity-0 sm:translate-y-0 sm:translate-x-20"
    data-transition-enter-end="translate-y-0 opacity-100 sm:translate-x-0"
    data-transition-leave="transition ease-in duration-200"
    data-transition-leave-start="opacity-100"
    data-transition-leave-end="opacity-0"
  >
    <!--
      Notification panel, dynamically insert this into the live region when it needs to be displayed

      Entering: "transform ease-out duration-300 transition"
        From: "translate-y-2 opacity-0 sm:translate-y-0 sm:translate-x-2"
        To: "translate-y-0 opacity-100 sm:translate-x-0"
      Leaving: "transition ease-in duration-100"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div class="flex items-center">
      <div class="flex-shrink-0">
        <%= flash_icon key %>
      </div>
      <div class="ml-3">
        <p class="text-sm font-medium"><%= value %></p>
      </div>
      <div class="ml-auto pl-3">
        <div class="-mx-1.5 -my-1.5">
          <button type="button" data-action="flash#dismiss" class="inline-flex rounded-md p-1.5 focus:outline-none focus:ring-2 focus:ring-offset-2 <%= flash_btn_classes key %>">
            <span class="sr-only">Dismiss</span>
            <svg class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path d="M6.28 5.22a.75.75 0 00-1.06 1.06L8.94 10l-3.72 3.72a.75.75 0 101.06 1.06L10 11.06l3.72 3.72a.75.75 0 101.06-1.06L11.06 10l3.72-3.72a.75.75 0 00-1.06-1.06L10 8.94 6.28 5.22z"/>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<%= turbo_frame_tag "modal" do %>
  <div
    data-controller="modal"
    class="relative z-30" aria-labelledby="modal-title" role="dialog" aria-modal="true"
  >
    <!--
      Background backdrop, show/hide based on modal state.

      Entering: "ease-out duration-300"
        From: "opacity-0"
        To: "opacity-100"
      Leaving: "ease-in duration-200"
        From: "opacity-100"
        To: "opacity-0"
    -->
    <div
      data-modal-target="backdrop"
      data-transition-enter="ease-out duration-300"
      data-transition-enter-start="opacity-0"
      data-transition-enter-end="opacity-100"
      data-transition-leave="ease-in duration-200"
      data-transition-leave-start="opacity-100"
      data-transition-leave-end="opacity-0"
      class="fixed inset-0 transition-opacity bg-black bg-opacity-50"
    ></div>

    <div class="fixed inset-0 z-10 overflow-y-auto">
      <div class="flex items-end justify-center min-h-full p-4 overflow-auto text-center sm:items-center sm:p-0">
        <!--
          Modal panel, show/hide based on modal state.

          Entering: "ease-out duration-300"
            From: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
            To: "opacity-100 translate-y-0 sm:scale-100"
          Leaving: "ease-in duration-200"
            From: "opacity-100 translate-y-0 sm:scale-100"
            To: "opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
        -->
        <div
          data-modal-target="dialogPanel"
          data-transition-enter="ease-out duration-300"
          data-transition-enter-start="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          data-transition-enter-end="opacity-100 translate-y-0 sm:scale-100"
          data-transition-leave="ease-in duration-200"
          data-transition-leave-start="opacity-100 translate-y-0 sm:scale-100"
          data-transition-leave-end="opacity-0 translate-y-4 sm:translate-y-0 sm:scale-95"
          class="transform overflow-hidden rounded-md bg-white px-6 pt-10 pb-8 text-left shadow-xl transition-all
          max-w-[30rem] grow dark:bg-dark-grey my-20 lg:my-0 relative"
        >
          <button
            class="absolute top-2 right-2"
            data-modal-target="closeBtn"
            data-action="click->modal#close"
          >
            <%= svg_tag 'icon-modal-cross', class: 'w-5 h-5 text-medium-grey' %>
          </button>

          <%= yield %>
        </div>
      </div>
    </div>
  </div>

<% end %>

app/views/shared/_nav.html.erb
<nav class="flex min-w-max grow flex-col gap-5 overflow-x-auto py-4 pr-6">
  <p class="px-6 uppercase text-heading-s text-medium-grey xl:px-8">
    All boards
    (<%= @user_boards.size %>)
  </p>
  <div id="boards-nav-list" class="flex flex-col">
    <% @user_boards.each do |board| %>
      <%= link_to board, class: "flex gap-3 items-center px-6 xl:px-8 py-4 text-heading-m rounded-r-full #{ current_page?(board_path(board)) ? 'text-white bg-main-purple' : 'text-medium-grey hover:bg-main-purple/10 hover:text-main-purple'} dark:hover:bg-white dark:hover:text-main-purple transition-color ease duration-200" do %>
        <%= svg_tag 'icon-board' %> <%= board.name %>
      <% end %>
    <% end %>
    <%= link_to new_board_path, data: { turbo_frame: 'modal' }, class: 'flex items-center gap-3 rounded-r-full px-6 py-4 text-heading-m text-main-purple hover:bg-main-purple/10 xl:px-8' do %>
      <%= svg_tag 'icon-board' %>
      + Create new board
    <% end %>
  </div>

  <div class="ml-6 flex items-center justify-center gap-6 rounded-md py-3.5 bg-light-grey text-medium-grey dark:bg-very-dark-grey md:mt-auto">
    <%= svg_tag 'icon-light-theme' %>
    <!-- Enabled: "bg-indigo-600", Not Enabled: "bg-gray-200" -->
    <button
      data-controller="theme-switcher"
      data-action="click->theme-switcher#toggleTheme"
      type="button"
      class="relative inline-flex h-6 w-11 flex-shrink-0 cursor-pointer rounded-full border-2 border-transparent transition-colors duration-200 ease-in-out bg-main-purple dark:bg-medium-grey hover:bg-main-purple-hover focus:outline-none focus:ring-2 focus:white focus:ring-offset-2"
      role="switch"
      aria-checked="false"
    >
      <span class="sr-only">Use setting</span>
      <!-- Enabled: "translate-x-5", Not Enabled: "translate-x-0" -->
      <span
        data-theme-switcher-target="icon"
        aria-hidden="true"
        class="pointer-events-none inline-block h-5 w-5 translate-x-0 transform rounded-full bg-white shadow ring-0 transition duration-200 ease-in-out"
      ></span>
    </button>
    <%= svg_tag 'icon-dark-theme' %>
  </div>
</nav>

app/views/shared/_sidebar.html.erb
<aside
  data-controller="sidebar"
  data-sidebar-open-value="true"
  class="hidden shrink-0 flex-col border-r bg-white transition-[flex-basis] duration-300 ease-out basis-[16.375rem] border-lines-light dark:bg-dark-grey dark:border-lines-dark md:flex xl:basis-[18.75rem]">
  <div class="flex shrink-0 basis-20 items-center px-6 dark:bg-dark-grey xl:basis-24 xl:px-8">
    <%= svg_tag 'logo-dark', class: 'dark:hidden' %>
    <%= svg_tag 'logo-light', class: 'hidden dark:block' %>
  </div>

  <%= render partial: 'shared/nav' %>


  <button
    data-sidebar-target="closeBtn"
    data-action="click->sidebar#toggle"
    class="mr-6 mb-8 flex leading-none items-center gap-3 rounded-r-full px-6 py-4 text-heading-m text-medium-grey
    hover:bg-main-purple/10 xl:px-8 dark:hover:text-main-purple dark:hover:bg-white z-10">
    <%= svg_tag 'icon-hide-sidebar' %>
    <span>
      Hide Sidebar
    </span>
  </button>

  <button
    id="invisible_sidebar_btn"
    class=" mr-6 mb-8 leading-none overflow-x-auto min-w-max hidden items-center gap-3 rounded-r-full px-6 py-4 text-heading-m text-medium-grey hover:bg-main-purple/10 xl:px-8 dark:hover:text-main-purple dark:hover:bg-white invisible">
    <%= svg_tag 'icon-hide-sidebar' %>
    <span>
      Hide Sidebar
    </span>
  </button>
</aside>

app/views/shared/_topbar.html.erb
<header class="z-20 flex items-center gap-4 px-4 bg-white shrink-0 basis-16 border-lines-light dark:bg-dark-grey dark:border-lines-dark md:basis-20 md:gap-6 md:border-b md:px-6 xl:basis-24 xl:gap-8 xl:px-8">

  <div
    id="topbar_logo"
    class="md:hidden"
  >
    <%= svg_tag 'logo-mobile', class: 'md:hidden' %>
    <%= svg_tag 'logo-dark', class: 'hidden md:block dark:hidden' %>
    <%= svg_tag 'logo-light', class: 'hidden md:dark:block' %>
  </div>

  <div
    id="topbar_logo_separator"
    class="hidden w-px h-full border-r border-lines-light dark:border-lines-dark md:hidden"
  >
  </div>

  <div class="flex items-center gap-2">
    <h1 class="text-heading-l dark:text-white xl:text-heading-xl"><%= @board&.name || 'Kanban App' %></h1>
    <button
      class="md:hidden"
      id="mobile_nav_popup_btn"
    >
      <%= svg_tag 'icon-chevron-down', id: 'icon_chevron_down' %>
      <%= svg_tag 'icon-chevron-up', id: 'icon_chevron_up', class: 'hidden' %>
    </button>
  </div>

  <%= button_to new_task_path, method: :get, disabled: @board.nil? || @board.lists.empty?, form_class: 'ml-auto', form: { data: { turbo_frame: 'modal' } }, class: 'rounded-3xl text-white px-4.5 bg-main-purple py-2.5 text-heading-m enabled:hover:bg-main-purple-hover disabled:cursor-not-allowed disabled:opacity-25 md:py-3.5 md:px-6' do %>
    <%= hidden_field_tag :board_id, @board&.id %>
    <%= svg_tag 'icon-add-task-mobile', class: 'md:hidden' %>
    <span class="hidden md:block">+ Add New Task</span>
  <% end %>

  <%= render 'shared/dots_menu' do %>
    <% if @board.present? %>
    <%= link_to 'Edit board', edit_board_path(@board), data: { turbo_frame: 'modal' }, class: 'px-4' %>
    <%= link_to 'Delete board', confirm_destroy_board_path(@board), data: { turbo_frame: 'modal' }, class: 'px-4 text-red' %>
    <hr class="h-px border-lines-light dark:border-lines-dark">
    <% end %>
    <%= link_to 'Edit Profile', edit_user_registration_path, class: 'px-4' %>
    <%= link_to 'Log Out', destroy_user_session_path, class: 'px-4', data: { turbo_method: :delete } %>
  <% end %>
</header>



<%= render 'shared/topbar/mobile_nav_popup' %>